* My personal blog (martinsos.com)

** Design principle
I want my blog to be as simple and intuitive for me to use as possible.
Being able to start writing immediatelly after not using it for longer time beats having rich features. I like it minimal anyway.

That means sticking to a small set of evergreen, stable tech that I know well (emacs, bash, Makefile) + keeping its overall structure and features simple.

** Overview
- =src/= - all the source material that makes up the blog: pages, posts, html layouts (=layout.el=), css, js, images, ...
  - There is a common =layout.el= at the top level, and then there is a post-specific =layout.el= in =posts/= dir.
- =build/= - build pipeline: logic (mostly) in elisp that takes all from =src/= and produces a web page from it in =dist/=.
- =dist/= - an actual blog that can be published (distributed) as a web page.
- =tools/= - helper tooling, like image optimization and font subsetting.

** Development / writing
*** Build commands
- ~make serve~ to run a simple dev server that hosts the built blog (in =dist/=) on =localhost=.
- ~make build-inc~ (or just ~make~) to generate/build the blog from =src/= in =dist/=.
  This is incremental build, so deleted files will remain around and state in =dist/= can become wrong with time due to that, but is fast and practical for development.
- ~make build-clean~ to generate/build the blog from =src/= from scratch in =dist/=.
  This is clean build, therefore slow because it first deletes all from =dist/=, but it guarantees that contents of =dist/= will correctly correspond to contents from =src/=. Slow, but guarantees correctness.

***  Typical workflow
- Create new or edit existing post in =src/posts/=. Its images/assets goes into the dir next to it with the same name as the post file.
- When adding an image, run ~tools/optimize-image.sh path/to/image.png~ to produce a =.webp= next to it, and reference the =.webp= from the org file.
  The build only copies =.webp= images to =dist/=; the original =.png=/=.jpg= is kept in the repo as a master but is not published.
- ~make serve~ once in the terminal at the start of the writing session
- ~project-compile~ (or ~project-recompile~ on later calls) to re-build the project from emacs as needed while editing the file
- ~make build-clean~ when preparing to publish the blog.

** Publishing
I am hosting the blog as static page on Cloudflare.

First, I should make sure that content in =dist/= is what I want to publish.
Normally I do ~make build-clean~ and then ~make serve~ to verify it is all looking good.

Then, ~make publish~ to publish the contents of =dist/=!

** Misc
- For the sake of simplicity, I on purpose don't have sitemap.xml, since this blog is simple enough and well internally linked that having one wouldn't bring any value.

** Mentions
I got initial idea and push for implementing this blog primarily in elisp and org from this great video from System Crafters: [[https://systemcrafters.net/publishing-websites-with-org-mode/building-the-site/][Build Your Website with Org Mode]].

** TODO
- [ ] Add favicon.
- [ ] Add RSS?
  - https://list.orgmode.org/20110806215735.GA19596@facies.mindmutation.net/
- [ ] Do something with the FILETAGS?
- [ ] Maybe add "Snippets" next to "Posts", for small stuff. Microblogging.
